name: Node.js CI
description: Run basic Node.js CI steps
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run test --if-present
    - run: npm run lint --if-present
